---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
# Set data dir
data.directory <- "./data"

# Set zip archive data file name
archive.file.name <- "activity.zip"

# Set path/to/zip archive data file 
archive.data.file <- file.path(data.directory, archive.file.name)

# Extract zip archive data file
unzip(archive.data.file, exdir = data.directory)

# Set csv data file name
csv.file.name <- "activity.csv"

# Set path/to/csv data file 
csv.data.file <- file.path(data.directory, csv.file.name)

# Read csv data file
my.frame <- read.csv(file = csv.data.file, 
                     stringsAsFactors = FALSE, 
                     colClasses = c("integer", "Date", "integer")
            )

## What is mean total number of steps taken per day?
# Compute total steps by day
require(dplyr)
total.steps <- summarise(group_by(my.frame, date), 
                         total = sum(steps, na.rm = TRUE)
               )

# Alternatively, use:
# total.steps <- my.frame %>%
#                 group_by(date) %>%
#                 summarise(total = sum(steps, na.rm = TRUE))

# Make a histogram of total steps by day
hist(total.steps$total, 
     main = "Total steps taken per day", 
     xlab = "Total steps taken")

# Compute mean and median total number of steps by day
mean.steps   <- mean(total.steps$total, na.rm = TRUE)
median.steps <- median(total.steps$total, na.rm = TRUE)

## What is the average daily activity pattern?

# Compute average number of steps per interval
require(dplyr)
interval.aves <- my.frame %>%
                   group_by(interval) %>%
                   summarise(ave.steps = mean(steps, na.rm = TRUE))

# Make a time series plot of interval vs. average number of steps
plot(ave.steps ~ interval, data = interval.aves, type = "l",
     main = "Average number of steps taken vs. Interval",
     xlab = "Interval", ylab = "Average number of steps taken"
     )

# Interval containing max average number of steps
interval.aves[interval.aves$ave.steps == max(interval.aves$ave.steps), 
              "interval"]
# Alternatively, do:
# subset(interval.aves, 
           interval.aves$ave.steps == max(interval.aves$ave.steps), 
           interval)
#
# -or,
# max.interval <- which(interval.aves$ave.steps == max(interval.aves$ave.steps))
# interval.aves[max.interval, "interval"]

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
